/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as KorvaWasteRouteImport } from './routes/korva-waste'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PressKitRouteImport } from './routes/press-kit'
import { Route as RoadmapRouteImport } from './routes/roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const KorvaWasteRoute = KorvaWasteRouteImport.update({
  id: '/korva-waste',
  path: '/korva-waste',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PressKitRoute = PressKitRouteImport.update({
  id: '/press-kit',
  path: '/press-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-study': typeof CaseStudyRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRoute
  '/korva-waste': typeof KorvaWasteRoute
  '/partner': typeof PartnerRoute
  '/press-kit': typeof PressKitRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-study': typeof CaseStudyRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRoute
  '/korva-waste': typeof KorvaWasteRoute
  '/partner': typeof PartnerRoute
  '/press-kit': typeof PressKitRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-study': typeof CaseStudyRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRoute
  '/korva-waste': typeof KorvaWasteRoute
  '/partner': typeof PartnerRoute
  '/press-kit': typeof PressKitRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-study'
    | '/faq'
    | '/insights'
    | '/korva-waste'
    | '/partner'
    | '/press-kit'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-study'
    | '/faq'
    | '/insights'
    | '/korva-waste'
    | '/partner'
    | '/press-kit'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-study'
    | '/faq'
    | '/insights'
    | '/korva-waste'
    | '/partner'
    | '/press-kit'
    | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudyRoute: typeof CaseStudyRoute
  FaqRoute: typeof FaqRoute
  InsightsRoute: typeof InsightsRoute
  KorvaWasteRoute: typeof KorvaWasteRoute
  PartnerRoute: typeof PartnerRoute
  PressKitRoute: typeof PressKitRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korva-waste': {
      id: '/korva-waste'
      path: '/korva-waste'
      fullPath: '/korva-waste'
      preLoaderRoute: typeof KorvaWasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-kit': {
      id: '/press-kit'
      path: '/press-kit'
      fullPath: '/press-kit'
      preLoaderRoute: typeof PressKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudyRoute: CaseStudyRoute,
  FaqRoute: FaqRoute,
  InsightsRoute: InsightsRoute,
  KorvaWasteRoute: KorvaWasteRoute,
  PartnerRoute: PartnerRoute,
  PressKitRoute: PressKitRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
